POST http://localhost:3000/transaction/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY3BmIjoiMTIzNDU2Nzg5MDEiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzUxNDE5MzQ5LCJleHAiOjE3NTE0MjY1NDl9.baM8ziBGCODIEZvenqvKgCd9kAdKJntw8x0Of7wUwJ8


{
  "paymentType": "credit_card",
  "transactionItems": [
    { "productId": 1 },
    { "productId": 4 }
  ]
}

###
GET http://localhost:3000/transaction/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY3BmIjoiMTIzNDU2Nzg5MDEiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzUxMzY5OTQ5LCJleHAiOjE3NTEzNzcxNDl9.V6goFmeRoaBUgYhcflC0ufWpiF5-lVwy1oqBopEV-ms


###
GET http://localhost:3000/transaction/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY3BmIjoiMTIzNDU2Nzg5MDEiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzUxMzY5OTQ5LCJleHAiOjE3NTEzNzcxNDl9.V6goFmeRoaBUgYhcflC0ufWpiF5-lVwy1oqBopEV-ms
