POST http://localhost:3000/users/register
Content-Type: application/json

{
  "fullName": "Mr Mystin",
  "username": "MrMstin",
  "email": "test@gmail.com",
  "password": "testetest",
  "cpf": "12345678901"
}

###

GET http://localhost:3000/users/listAll

###

GET http://localhost:3000/users/listOne/12345678901

###

PATCH http://localhost:3000/users/update/12345678901

{
  "fullName": "Mystin Mr",
  "email": "test2@gmail.com",
  "password": "testetest2",
}

###

DELETE http://localhost:3000/users/delete/12345678901